#!/bin/bash
set -euo pipefail
IFS=$'\n\t'
trap 'echo FATAL ERROR EXIT CODE $? AT $0:$LINENO' ERR


which make || sudo apt-get install -y build-essential
which nvcc || sudo apt-get install -y nvidia-cuda-toolkit

openni2d='OpenNI-Linux-x64-2.2'
if ! test -d "$openni2d" ; then
    openni2='OpenNI-Linux-x64-2.2.0.33'
    pushd lib
    #wget --no-clobber https://s3.amazonaws.com/com.occipital.openni/$openni2.tar.bz2
    popd

    cp --verbose ./lib/$openni2.tar.bz2 .
    tar xvf $openni2.tar.bz2
fi

which cmake || sudo apt-get install -y cmake
sudo apt-get install -y freeglut3-dev

cd InfiniTAM
cmake "$(realpath .)" -DOPEN_NI_ROOT="$(realpath ../$openni2d)"
