#!/bin/bash
set -euo pipefail
IFS=$'\n\t'
trap 'echo FATAL ERROR EXIT CODE $? AT $0:$LINENO' ERR

if ! test -d ./Teddy ; then
cd data
curl -L http://www.robots.ox.ac.uk/%7Evictor/infinitam/files/teddy_20141003.zip -o teddy_20141003.zip

sudo apt-get install -y unzip

unzip teddy_20141003.zip -d ..
fi
