#!/bin/bash
set -euo pipefail
IFS=$'/n/t'
trap 'echo FATAL ERROR EXIT CODE $? AT $0:$LINENO' ERR

# ./scripts/dist
# WITH_CUDA=true ./scripts/dist

INSTALL_CUDA_DRIVERS="true"

if test "${WITH_CUDA:-}" == "true" ; then
    WITH_CUDA=".WITH_CUDA"

    INSTALL_CUDA_DRIVERS="./install-cuda-drivers"
else
    WITH_CUDA=""
fi

mkdir -p dist

cp --verbose ./InfiniTAM/build/Apps/InfiniTAM_cli/InfiniTAM_cli "./dist/InfiniTAM_cli$WITH_CUDA"
cp --verbose ./InfiniTAM/build/Apps/InfiniTAM/InfiniTAM "./dist/InfiniTAM$WITH_CUDA"
cp --verbose ./data/download-teddy ./dist
cp --verbose ./scripts/install-cuda-drivers ./dist

# libglut.so.3: dynamically linked runtime dependency:
function f() {
    output="./dist/InfiniTAM$1.with-teddy$WITH_CUDA.sh"

    echo -n "#!/bin/bash
    set -euo pipefail
    ./download-teddy
    
    test -f /usr/lib/x86_64-linux-gnu/libglut.so.3 || sudo apt-get install -y freeglut3 || ( sudo apt-get update && sudo apt-get install -y freeglut3 ) 

    function run() {
        ./InfiniTAM$1$WITH_CUDA Teddy/calib.txt 'Teddy/Frames/%04i.ppm' 'Teddy/Frames/%04i.pgm'
    }
    run || ($INSTALL_CUDA_DRIVERS && run) || {
        echo 'STILL NOT WORKING You will need to reboot for any newly installed nvidia driver to work! Known Issue: WSL always segfaults after quitting even normally...'
        exit 1
    }
    " > "$output"
    chmod +x "$output"
}

f ''
f '_cli'
