#!/bin/bash
set -euo pipefail
IFS=$'\n\t'
trap 'echo FATAL ERROR EXIT CODE $? AT $0:$LINENO' ERR

sudo apt-get purge -y nvcc-tools || true
sudo apt-get purge -y nvidia-cuda-toolkit || true
sudo apt-get purge -y cuda-toolkit || true
sudo apt-get purge -y cuda-toolkit-12.3 || true
sudo apt-get purge -y cuda-12.3 || true
sudo apt-get purge -y cuda-repo-ubuntu2204-12-3-local || true
sudo apt-get autoremove -y

# dpkg -l 'cuda*'
hash -r # remove any references to old nvcc

# installation instructions from https://developer.nvidia.com/downloads
# https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=deb_local
cd /tmp

#wget --no-clobber https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
#sudo mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600
#wget --no-clobber https://developer.download.nvidia.com/compute/cuda/12.3.1/local_installers/cuda-repo-ubuntu2204-12-3-local_12.3.1-545.23.08-1_amd64.deb
#sudo apt-get -y install ./cuda-repo-ubuntu2204-12-3-local_12.3.1-545.23.08-1_amd64.deb
#sudo cp /var/cuda-repo-ubuntu2204-12-3-local/cuda-*-keyring.gpg /usr/share/keyrings/
#sudo apt-get update
#sudo apt-get -y install cuda-toolkit-12-3
#sudo apt-get -y install cuda-toolkit
# should not be necessary...
#export PATH="/usr/local/cuda-12.3/bin:$PATH"

wget --no-clobber https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
sudo mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600
wget --no-clobber https://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda-repo-ubuntu2204-11-8-local_11.8.0-520.61.05-1_amd64.deb
sudo apt-get install -y ./cuda-repo-ubuntu2204-11-8-local_11.8.0-520.61.05-1_amd64.deb
sudo cp /var/cuda-repo-ubuntu2204-11-8-local/cuda-*-keyring.gpg /usr/share/keyrings/
sudo apt-get update
#sudo apt-get -y install cuda
sudo apt-get -y install cuda-11-8
sudo apt-get update
sudo apt-get install -y cuda

export PATH="/usr/local/cuda-11.8/bin:$PATH"
nvcc --version
